In [39]:
#We'll create a model for a telecommunication company, to predict when its customers will leave for a competitor, so that they can take some action to retain the customers.

In [40]:
#A telecommunications company is concerned about the number of customers leaving their land-line business for cable competitors. They need to understand who is leaving. Imagine that you’re an analyst at this company and you have to find out who is leaving and why.


In [41]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pylab as pl
import scipy.optimize as opt


In [42]:
df=pd.read_csv('ChurnData.csv')
df.head()

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   longmon  ...    pager  internet  callwait  confer  ebill  loglong  logtoll  \
0     4.40  ...      1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1     9.45  ...      0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2     6.30  ...      0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3     6.05  ...      1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4     7.10  ...      0.0       0.0       1.0     1.0    0.0    1.960    3.091   

   lninc  custcat  churn  
0  4.913      4.0    1.0  
1  3.497      1.0    1.0  
2  3.401      3.0    0.0  
3  4.331      4.0    0.0  
4  4.382      3.0    0.0  

[5 rows x 28 columns]

In [43]:
#So our first step to convert datframe into array
#lets find 
df.columns

Index(['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',
       'callcard', 'wireless', 'longmon', 'tollmon', 'equipmon', 'cardmon',
       'wiremon', 'longten', 'tollten', 'cardten', 'voice', 'pager',
       'internet', 'callwait', 'confer', 'ebill', 'loglong', 'logtoll',
       'lninc', 'custcat', 'churn'],
      dtype='object')

In [44]:
#we weil select online some imp features
data=df[['tenure','age','address','income','ed','employ','equip','callcard','wireless','churn']]
data.head()

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   churn  
0    1.0  
1    1.0  
2    0.0  
3    0.0  
4    0.0

In [45]:
#Our binary values have float,,,lets convert into int
data["churn"]=data[['churn']].astype('int')
data.head()

C:\Users\vinod\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   churn  
0      1  
1      1  
2      0  
3      0  
4      0

In [46]:
data.shape

(200, 10)

In [47]:
#lets divide them into X and y 
X=np.asanyarray(data[['tenure','age','address','income','ed','employ','equip','callcard','wireless']])
y=np.asanyarray(data[['churn']])
# X.head(),y.head()  # this will be wrong because we have convert in arrays
X[5,:],y[:5]

(array([ 68.,  52.,  17., 120.,   1.,  24.,   0.,   1.,   0.]), array([[1],
        [1],
        [0],
        [0],
        [0]]))

In [48]:
#Now we are going to normalise ti 
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X)
X


array([[-1.13518441, -0.62595491, -0.4588971 , ..., -0.85972695,
         0.64686916,  1.56469673],
       [-0.11604313, -0.62595491,  0.03454064, ..., -0.85972695,
        -1.54590766, -0.63910148],
       [-0.57928917, -0.85594447, -0.261522  , ..., -0.85972695,
        -1.54590766, -0.63910148],
       ...,
       [-1.36680743, -0.7026181 , -0.16283445, ..., -0.85972695,
         0.64686916, -0.63910148],
       [-0.53296457, -0.85594447, -1.14970993, ..., -0.85972695,
         0.64686916,  1.56469673],
       [ 1.18104577,  0.67731925,  0.42929083, ...,  1.16316   ,
         0.64686916,  1.56469673]])

In [52]:
#Splitting the data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=.2,random_state=0)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (160, 9) (160, 1)
Test set: (40, 9) (40, 1)


In [53]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression(C=0.01,solver='liblinear')
LR.fit(X_train,y_train)

C:\Users\vinod\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [69]:
y_pred=LR.predict_proba(X_test)
y_pred

array([[0.54, 0.46],
       [0.42, 0.58],
       [0.44, 0.56],
       [0.73, 0.27],
       [0.58, 0.42],
       [0.67, 0.33],
       [0.75, 0.25],
       [0.47, 0.53],
       [0.65, 0.35],
       [0.44, 0.56],
       [0.55, 0.45],
       [0.75, 0.25],
       [0.6 , 0.4 ],
       [0.77, 0.23],
       [0.68, 0.32],
       [0.45, 0.55],
       [0.48, 0.52],
       [0.83, 0.17],
       [0.49, 0.51],
       [0.58, 0.42],
       [0.71, 0.29],
       [0.6 , 0.4 ],
       [0.72, 0.28],
       [0.44, 0.56],
       [0.72, 0.28],
       [0.39, 0.61],
       [0.63, 0.37],
       [0.49, 0.51],
       [0.41, 0.59],
       [0.46, 0.54],
       [0.45, 0.55],
       [0.43, 0.57],
       [0.59, 0.41],
       [0.59, 0.41],
       [0.41, 0.59],
       [0.68, 0.32],
       [0.55, 0.45],
       [0.59, 0.41],
       [0.55, 0.45],
       [0.52, 0.48]])

In [65]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print('accuracy :' , accuracy_score(y_test,y_pred))

accuracy : 0.75


In [66]:
#lets find one more evalution ..
#Jaccard Evaluation Score
from sklearn.metrics import jaccard_similarity_scoraccard_similarity_score(y_test,y_pred)

0.75